### ISSUE TITLE
1番目のエラーメッセージを表示するかどうか

### ISSUE THREAD

**Issue by shinespark** [KazuakiM/vim-qfstatusline#6]
前回PRを出した辺りから使わせていただいてます。
vim-watchdogsとの併用が恐らく前提となっているので、
vim-qfstatuslineの方では最初のエラーメッセージを出力するのではなく、エラー総数を全面に表示した方がよいのかなと思ってます。

## 現行
![screen shot 2016-12-20 at 12 45 09](https://cloud.githubusercontent.com/assets/12206768/21337816/f1840658-c6b3-11e6-9547-1b449521e8b8.png)

##  改案
![screen shot 2016-12-20 at 12 48 54](https://cloud.githubusercontent.com/assets/12206768/21337815/ef31ea64-c6b3-11e6-8910-1dd20349ac29.png)

試しに PR #5 で出してみました。

**Comment by shinespark** [comment]
仕様変わってるのでテスト落ちてますね...

あくまで案なので、OKでしたらテスト更新します。今のままでしたらそのままCloseで大丈夫です。

**Comment by KazuakiM** [comment]
エラー総数自体は```(2)```という形で表示していますね。
私はステータスラインに大量にアイコンなどを表示しないため、メッセージがより長く出てくれた方が嬉しいのですが、
```L3(2)```という表示でしたら、ステータスラインのスペースを取らずに良いかもしれません。
PRの内容を見た限りですが、quickfixをこのpluginだけに利用する想定に見受けられました。
quickfixは便利機能なので、もっと多用した方が良いかもです。

**Comment by shinespark** [comment]
なるほど、quickrunやvimgrepなどとの併用も考慮した結果だったのですね。
vim-watchdogsメインで利用していたのでそこまで配慮に至りませんでした。

用途を狭めてしまうのでこの変更はrejectしていただいて結構です。ありがとうございました。
(Ownerは @KazuakiM さんなので、確認後issue, pr共にクローズしていただいて結構です。 )
